hoistPattern:
  - '*'
hoistedDependencies:
  '@iconify/types@2.0.0':
    '@iconify/types': private
  '@lit-labs/ssr-dom-shim@1.4.0':
    '@lit-labs/ssr-dom-shim': private
  '@lit/reactive-element@2.1.1':
    '@lit/reactive-element': private
  '@types/trusted-types@2.0.7':
    '@types/trusted-types': private
  argparse@2.0.1:
    argparse: private
  lit-element@4.2.1:
    lit-element: private
  lit-html@3.3.1:
    lit-html: private
included:
  dependencies: true
  devDependencies: false
  optionalDependencies: true
injectedDeps: {}
layoutVersion: 5
nodeLinker: isolated
packageManager: pnpm@10.17.0
pendingBuilds: []
prunedAt: Mon, 22 Sep 2025 01:33:15 GMT
publicHoistPattern: []
registries:
  '@jsr': https://npm.jsr.io/
  default: https://registry.npmjs.org/
skipped: []
storeDir: /pnpm/store/v10
virtualStoreDir: .pnpm
virtualStoreDirMaxLength: 120
