# configuration file for production environment

logger: log4perl
engines:
   logger:
      log4perl:
        category: Game::EvonyTKR::Dancer2

# the log level for this environment
# core is the lowest, it shows Dancer2's core log messages as well as yours
# (debug, info, warning and error)
log: info


# hide errors
show_stacktrace: 0

# disable server tokens in production environments
no_server_tokens: 1
