# configuration file for production environment

logger: log4perl
log: warning
engines:
   logger:
      log4perl:
         config_file: share/log4perl.conf

# hide errors
show_stacktrace: 0

# disable server tokens in production environments
no_server_tokens: 1
