use v5.42.0;
use experimental qw(class);
use utf8::all;
use File::FindLib 'lib';
require Data::Printer;
require Game::EvonyTKR::Shared::Constants::BuffConstants;
require Game::EvonyTKR::Shared::Constants::GeneralConstants;
use namespace::autoclean;

package Game::EvonyTKR::Role::Buff::Value {
  use Mojo::Base 'Game::EvonyTKR::Role::Common';
  use Mojo::Base 'Game::EvonyTKR::Shared::Constants::BuffConstants',    -role;
  use Mojo::Base 'Game::EvonyTKR::Shared::Constants::GeneralConstants', -role;
  use Carp;
  use File::FindLib 'lib';
  use Log::Any qw($log);

  my $logger = $log;

  sub validate ($self) {
    my @errors;

    if ($self->unit ne 'flat' and $self->unit ne 'percentage') {
      push @errors, "unit must be 'flat' or 'percentage' not '$self->unit'";
    }
    unless (Scalar::Util::looks_like_number($self->number)) {
      push @errors,
        "number must be a positive floating point number, not '$self->number'";
    }

    if (scalar @errors >= 1) {
      $self->logger->error(join ', ', @errors);
      croak(join ', ', @errors);
      return;
    }
  }

}
1;

__END__

#ABSTRACT: Stores the Value for Buff objects

=pod

=head1 DESCRIPTION

A Buff's value cannot be properly understood, or used, as a simple number.  Rather,
it must be considered in light of its unit.  A Buff/Debuff Value is either a flat
value (which *could* be considered a simple number), or a percentage (which would
need to be divided by 100 and then multiplied against some base value before it
could be treated as a simple number).

This stores both the numeric portion and the string based unit designator for the Value.

=cut

=cut

# ABSTRACT: Values for Evony TKR Buffs

=attr $number

the numeric value as an Integer for Buff.  Defaults to 0.
=cut

=method number()

the auto generated getter for the $number attribute
=cut

=method unit()

this string value will reject anything other than the litteral values 'percentage' and 'flat'.
It defaults to 'percentage'.
=cut

=method unit()

the autogenerated getter for the $unit attribute
=cut
