#cloud-config
package_update: true
package_upgrade: true
packages:
  - autoconf
  - autoconf-archive
  - automake
  - bison
  - build-essential
  - certbot
  - curl
  - flex
  - gcc
  - gcc-13-locales
  - gettext
  - git
  - gnu-standards
  - graphviz
  - libgd-dev
  - libgraphviz-dev
  - libssl-dev
  - libtool
  - libzip-dev
  - make
  - nginx
  - openssh-server
  - pipx
  - pkg-config
  - plocate
  - postgresql
  - postgresql-contrib
  - postgresql-server-dev-16
  - python3
  - python3-certbot-nginx
  - python3-pip
  - rsync
  - sqlite3
  - sysstat
  - unattended-upgrades
  - unzip
  - update-notifier-common
users:
  - default
  - name: appuser
    homedir: /opt/prefix
    system: true
    shell: /sbin/nologin
    groups: www-data
  - name: luke
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    groups: users, admin, adm, man, sudo, operator, src, staff, crontab
    ssh_authorized_keys:
      - ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBABn9dVXygIvLoJrcSA71/PNcPRPxg0FBmU1QkVIPToc4cfBP9oiyGkiRJ33kz9zaL1lseB75XGoz01W0lex2/9zjAHGxDdo9byoemhtKlGXoWZ43rRfuZtXPQkLLFhONmVfG1eK5Bct4M314N4WrmbxyRg5froEvK10yqrPzeagleCywQ== lschiere@a07817adb134.ant.amazon.com
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDos5u8SSJXO8BcmKrjfUjxz8y9KwmfTXfhetEcPQ1bSCY/fIaebvKJG4YJ0OmFKBQLW63MTnKp9iScw9OQp0mE5q/EMQj30iXu/q6ufYoGG5U9NAr4D6wH9XEUvwS6TrDXGphseGDxZk1ZspfdMR+c/XAALgyNVnzhaqW7k1KNJjUzw9ZzVFTDWcYOKFPgOorQIjTmn3y1B6NhQ179N7yB/6NiOKLn3gwNB3/jm9WidnnGHXA940nFIBNv7Ml0jSRChXd/57+VahVzqAxo8NlpiKfLHQPj7VjwBA7s7/gB67X7vnr/sERda8EmEu0sWgCZ9V1i1eOn0B2SKojhXJIpI2kMLDrZIP0RR9hdgqatRE13wNTYzbGPlSUhOCDaiiHOuBYqNbFYhCfV0fPo0CuHPn/04pbFnRU5KDdsyhjk4oa90Df1oq/X3bfAtj1d0gfrt0SVBa9TUh4Hi6vYFBQ5YRmY3YPk2xUsJxnDTYmocizqYZLU6RCPwVMkZrxIOflS96LGVLoqVVLRXLm1UVAkGViWB9ezhT1fxoyjF2s9xT2oRY8bmro+cep/N8Dk9YfAGrJRjLGKu185+ssB+WfpB2ZjA3OMK+6NPwn573S4lO0ftatbqOZSUQ4U4zxZJE8gMtBs8tAhdRsBj6JRd30OB2bSWdwiaEErPzvAaW3uzQ== luke@schierer@opus001.schierer.org
      - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEAzzFE5saXFWaM8aJscVuqSk48EcrcOvZ1tdFSgyQkK7eH/oBnZGvAyouRtmpavwUDIUelpmfVyaMdDX606ml5ZAQkodn4Nhje5v1jJ/32Wi3gIs6kosjdsB8ew6v2LIWuVVJrz+ZsjaoALAqjYmetPbtKo42u6Ai95otWBt2NxEUZx2LrLG/6MtxrXspcrmatDZGDiDSz7KOHP2O4j7c48tLG5naaLeT5ZoPRFNhVUVujyedc1s02TtHbvQ3sICgwNxx9B4HkFLuegtWhYwFretZJzhDrEY2olFtwbQR2r4TGJLYIrudj6G06HN7zfVf7Csd+LFW7HF5aztGHwm3g907jjzmG1U3ptfAqmR5bffJXhlbemD/++0Hs+f4ta2eevTZZUwRnGpM1Y9lfFip2d3UiiNgdblhbnmPlEPZhkPgcxE5rwsHClnZ2rUsDgTaWyRoiegvxIGmArcTt5133/Y8eNkCS9/opxzqRsmZ0eNcovyjpCXoa/CXT37uOZgzjf9DcVZCtenIZyZPGLxYrqlwOJBKHLYua6k1+fQ+/v+Qq+/R0RtMW6Of3L8akx+2MQnvG4lwutVsih0Ohg49G1JkJn6/5h8NIDbE5zcBQIa4tTQOO9I3A32pjyg9XH2WnUl5PZDBOaj/TKM6t+qMlLQwePZCpZ62nQ4rL3vRCPjk= lukeschierer@minimus.local
runcmd:
  - export HOSTNAME='REPLACEHOSTNAME'; hostname ${HOSTNAME}
  - export HOSTNAME='REPLACEHOSTNAME'; hostnamectl set-hostname ${HOSTNAME}
  - export HOSTNAME='REPLACEHOSTNAME'; echo "127.0.1.1 ${HOSTNAME} ${HOSTNAME}.localdoamin" >> /etc/hosts
  - PIPX_HOME=/usr/local/ PIPX_BIN_DIR=/usr/local/bin PIPX_MAN_DIR=/usr/local/ /usr/bin/pipx install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz || echo 'cfn-bootstrap failed' >> /var/log/boostrap.log
  - ln -sf /usr/local/bin/cfn-* /usr/bin/ || true
  - service procps force-reload
  - systemctl is-active sysstat
  - add-apt-repository -y universe
  - apt-get update
  - apt-get dist-upgrade -y
  # Steps to install amazon-ssm-agent manually
  - apt-get remove --purge -y snapd
  - curl "https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_arm64/amazon-ssm-agent.deb" -o "/tmp/amazon-ssm-agent.deb"
  - dpkg -i /tmp/amazon-ssm-agent.deb
  - systemctl enable amazon-ssm-agent
  - systemctl start amazon-ssm-agent
  - mkdir -p /opt/prefix/var/run
  - mkdir -p /opt/prefix/bin
  - /usr/sbin/groupmod -a appuser -U luke
  - chown -R appuser:www-data /opt/prefix
  - sudo -u appuser touch /opt/prefix/.bash_profile
  - echo 'export PATH="/opt/prefix/.local/bin/:$HOME/bin:$PATH"' >> /opt/prefix/.bash_profile
  - mkdir /etc/nginx/ssl
  # if there is not a cert present where the nginx config states, then
  # when certbot runs, it checks the nginx config syntax for correctness and it will fail
  - openssl req -x509 -newkey rsa:2048 -keyout /etc/nginx/ssl/evonytkrtips.net.key -out /etc/nginx/ssl/evonytkrtips.net.crt -days 365 -nodes -subj "/C=US/ST=State/L=City/O=Org/OU=OrgUnit/CN=localhost"
  - chown -R www-data:www-data /etc/nginx/ssl
  # several of the previous processes cache quite a bit, prevent OOM
  # this is *probably* only needed in dev, as even without this it works fine
  # on the auto retry systemctl does
  - sync && echo 3 > /proc/sys/vm/drop_caches
  - systemctl enable unattended-upgrades
  - mkdir -p /opt/prefix/var/log/Perl/dist/Game-EvonyTKR/
  - mkdir -p /home/luke/var/log/Perl/dist/Game-EvonyTKR/
  - chown -R appuser:www-data /opt/prefix/var
  - chown -R luke:luke /home/luke/var
  - find /opt/prefix/var -type d -exec chmod g+rx {} \;
  - chmod 644 /etc/logrotate.d/evonytkr
