#!/usr/bin/env perl
use v5.40.0;
use experimental qw(class);
use utf8::all;
use Carp;
use Cwd;
require Path::Tiny;
use File::FindLib 'lib';

# PODNAME: App::game-evonytkr
our $VERSION = 'v0.40.0';


# Start command line interface for application
use Game::EvonyTKR;

Game::EvonyTKR->run;

__END__
# ABSTRACT: command wrapper for the Game::EvonyTKR Mojolicious application

=pod

=head1 DESCRIPTION

This wrapper allows you to run the various Mojolicous::Command commands for the Game::EvonyTRK Mojolicious applicaiton

=cut
