use v5.42.0;
use utf8::all;
use File::FindLib 'lib';
require JSON::PP;
use namespace::autoclean;

package Game::EvonyTKR::Model::Buff::Value {
  use Mojo::Base 'Game::EvonyTKR::Model::Base';
  use Mojo::Base 'Game::EvonyTKR::Role::Constants::BuffConstants', -role;
  use Mojo::Base 'Game::EvonyTKR::Role::Constants::GeneralConstants', -role;
  use Carp;
  use File::FindLib 'lib';
  use overload
    '""'       => \&as_string,
    'bool'     => \&_isTrue,
    'fallback' => 0;

  has 'number' => 0;
  has 'unit'   => 'flat';

  sub clone ($self) {
    return __PACKAGE__->new(
      number => $self->number,
      unit   => $self->unit,
    );
  }

  sub validate ($self) {
    my @errors;

    if ($self->unit ne 'flat' and $self->unit ne 'percentage') {
      push @errors, "unit must be 'flat' or 'percentage' not '$self->unit'";
    }
    unless (Scalar::Util::looks_like_number($self->number)) {
      push @errors,
        "number must be a positive floating point number, not '$self->number'";
    }

    if (scalar @errors >= 1) {
      $self->logger->error(join ', ', @errors);
      croak(join ', ', @errors);
      return;
    }
  }

  sub to_hash ($self) {
    return {
      __CLASS__ => __PACKAGE__,
      number    => $self->number,
      unit      => $self->unit,
    };
  }

  sub TO_JSON {
    my $self = shift;
    return $self->to_hash();
  }

  sub as_string {
    my $self = shift;
    my $json =
      JSON::PP->new->utf8(1)
      ->canonical(1)
      ->allow_blessed(1)
      ->convert_blessed(1)
      ->encode($self->to_hash());
    return $json;
  }

  sub _isTrue ($self, $other = undef, $swap = undef) {
    return
         defined($self)
      && ref($self)
      && blessed($self)
      && $self->isa('Game::EvonyTKR::Model::Book');
  }
}
1;

__END__

#ABSTRACT: Stores the Value for Buff objects

=pod

=head1 DESCRIPTION

A Buff's value cannot be properly understood, or used, as a simple number.  Rather,
it must be considered in light of its unit.  A Buff/Debuff Value is either a flat
value (which *could* be considered a simple number), or a percentage (which would
need to be divided by 100 and then multiplied against some base value before it
could be treated as a simple number).

This stores both the numeric portion and the string based unit designator for the Value.

=cut

=cut

# ABSTRACT: Values for Evony TKR Buffs

=attr $number

the numeric value as an Integer for Buff.  Defaults to 0.
=cut

=method number()

the auto generated getter for the $number attribute
=cut

=method unit()

this string value will reject anything other than the litteral values 'percentage' and 'flat'.
It defaults to 'percentage'.
=cut

=method unit()

the autogenerated getter for the $unit attribute
=cut
