# PAGI WebServer Framework Configuration

# Stage: localDev, staging, production
stage: production

# Server configuration
server:
  host: 127.0.1.1
  port: 3000
  worker_threads: 4

modules:
  '^WebFramework::Module::AutoIndex': {}
  '^WebFramework::Module::SiteLogo':
    site_logo: share/public/images/TKRTipsLogo.svg
  Template:
    paths:
      - templates
      - templates/partials
      - ../PAGI-WebServer/templates
      - ../PAGI-WebServer/templates/partials
    conf:
      EVAL_PERL: 1

# Directory paths
css_dir: public/css
js_dir: public/js
images_dir: public/images
typescript_dir: src/ts
markdown_dir: share/pages
# relative to the public directory

# Pandoc modules to load
pandoc_modules:
  - commonmark
  - alerts
  - attributes
  - autolink_bare_uris
  - footnotes
  - implicit_header_references
  - pipe_tables raw_html
  - rebase_relative_paths
  - smart
  - gfm_auto_identifiers

log_base: Game-EvonyTKR
site_url: https://www.evonytkrtips.net
# Module-specific log levels
log_config:
  default: INFO
  'Game::EvonyTKR': INFO
  'WebFramework': INFO
  'Game::EvonyTKR::Controller::Books': WARN
  'Game::EvonyTKR::Controller::Generals': WARN
  'Game::EvonyTKR::Controller::Pairs': DEBUG
  'Game::EvonyTKR::External::AscendingAttributes': WARN
  'Game::EvonyTKR::External::General::Summarizer': DEBUG
  'Game::EvonyTKR::External::General::Pair::Summarizer': DEBUG
  'Game::EvonyTKR::External::General::Pair::LoadAllPairBuilder': DEBUG
  'Game::EvonyTKR::External::General::Pair::ReduceCoordinator': DEBUG
  'Game::EvonyTKR::External::General::Pair::CreatePairs': DEBUG
  'Game::EvonyTKR::External::General::ComputeBuffCache': 'INFO'
  'Game::EvonyTKR::External::General::Pair::BatchSummarizer': DEBUG
  'Game::EvonyTKR::External::Prebuild': DEBUG
  'Game::EvonyTKR::External': WARN
  'Game::EvonyTKR::Model::Buff': WARN
  'Game::EvonyTKR::Model::Buff::Matcher': WARN
  'Game::EvonyTKR::Model::Buff::Summarizer': WARN
  'Game::EvonyTKR::Model::Buff::Value': WARN
  'Game::EvonyTKR::Model::General': WARN
  'Game::EvonyTKR::Model': WARN
  'Game::EvonyTKR::Role::Persistence::Core': WARN
  'Game::EvonyTKR::Role::Persistence::Pairs': DEBUG
  'Game::EvonyTKR::Role::Persistence': WARN
  'Game::EvonyTKR::Role': WARN
  'Game::EvonyTKR::Service::DynamoDBPersistence': WARN
  'Game::EvonyTKR::Service::Persistence': 'INFO'
  'Game::EvonyTKR::Service': WARN
  'Game::EvonyTKR::Shared::Logger': WARN
  'Test::Package': 'TRACE'
  'Test': 'TRACE'
  'LinkChecker': DEBUG
