#!/usr/bin/env perl
use v5.42;
use experimental qw(class);
use utf8::all;
use File::FindLib 'lib';
use Getopt::Long;
use Carp;

require LinkChecker::Command;

my $startUrl = 'http://localhost:3000'; # default to assuming a local Mojolicious instance
my $debug = 0;
my $help = 0;

GetOptions(
  'url=s'   => \$startUrl,
  'debug'   => \$debug,
  'help'    => \$help,
) or die "Error in command line arguments\n";

if ($help) {
    print <<HELP;
Usage: $0 [options]

Options:
  --url=StartUrl  Url to start checking at
  --debug         enable debugging
  --help          Display this help message

HELP
exit 0;
}

my $checker = LinkChecker::Command->new(
  debug     => $debug,
  startUrl  => $startUrl,
);

$checker->execute();
