#!/usr/bin/env perl
use v5.42;
use experimental qw(class);
use utf8::all;
use File::FindLib 'lib';
use Getopt::Long;

# Load the Mojolicious app to access Minion
use Game::EvonyTKR;
my $app = Game::EvonyTKR->new;

# Register the tasks
require Game::EvonyTKR::External::LinkChecker::Worker;
require Game::EvonyTKR::External::LinkChecker::Coordinator;

Game::EvonyTKR::External::LinkChecker::Worker->register_task($app);
Game::EvonyTKR::External::LinkChecker::Coordinator->register_task($app);

my $start_url = 'http://localhost:3000';
my $workers = 4;
my $help = 0;
my $debug = 0;

GetOptions(
  'url=s' => \$start_url,
  'workers=i' => \$workers,
  'help' => \$help,
  'debug' => \$debug,
) or die "Error in command line arguments\n";

if ($help) {
  print <<HELP;
Usage: $0 [options]

Options:
  --url=URL       Starting URL to check (default: http://localhost:3000)
  --debug         enable debug mode
  --workers=N     Number of parallel workers (default: 4)
  --help          Show this help

HELP
  exit 0;
}

print "Starting distributed link check with $workers workers...\n";
print "Starting URL: $start_url\n";

my $job_id = $app->minion->enqueue('coordinate_link_check', [$start_url, $workers, $debug]);
print "Coordinator job started with ID: $job_id\n";
print "Monitor with: ./script/game_evonytkr minion job $job_id\n";
print "Or watch all jobs: ./script/game_evonytkr minion jobs\n";
