#!/usr/bin/env perl
use v5.40.0;
use experimental qw(class);
use utf8::all;
use Carp;

use Mojo::Base -strict;
use Mojo::File qw(curfile);
use lib curfile->dirname->sibling('lib')->to_string;
use Mojolicious::Commands;

# PODNAME: App::game-evonytkr
our $VERSION = 'v0.50.0';


# Start command line interface for application
require Game::EvonyTKR;

Mojolicious::Commands->start_app('Game::EvonyTKR');

__END__
# ABSTRACT: command wrapper for the Game::EvonyTKR Mojolicious application

=pod

=head1 DESCRIPTION

This wrapper allows you to run the various Mojolicous::Command commands for the Game::EvonyTRK Mojolicious applicaiton

=cut
