#!/usr/bin/env perl
use v5.40;
use experimental qw(class);
use utf8::all;

use Mojo::Base -strict;
use Mojo::File qw(curfile);
use lib curfile->dirname->sibling('lib')->to_string;

use Mojolicious::Commands;

# Start the app
Mojolicious::Commands->start_app('Game::EvonyTKR');
# ABSTRACT: command wrapper for the Game::EvonyTKR Mojolicious application

=pod

=head1 DESCRIPTION

This wrapper allows you to run the various Mojolicous::Command commands for the Game::EvonyTRK Mojolicious applicaiton

=cut
